#ifndef SPORT_VIDEO_ANALYSIS_FOR_BILLIARD_MATCHES_CLASSIFICATION_H
#define SPORT_VIDEO_ANALYSIS_FOR_BILLIARD_MATCHES_CLASSIFICATION_H

#include <iostream>
#include <opencv2/opencv.hpp>


#endif //SPORT_VIDEO_ANALYSIS_FOR_BILLIARD_MATCHES_CLASSIFICATION_H
